name: Coverage Build - Humble
on:
  workflow_dispatch:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  coverage:
    name: coverage build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: humble
    steps:
      - uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@0.3.5
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          # build all packages listed here
          package-name:
            ackermann_steering_controller
            admittance_controller
            bicycle_steering_controller
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            gripper_controllers
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_trajectory_controller
            position_controllers
            range_sensor_broadcaster
            steering_controllers_library
            tricycle_controller
            tricycle_steering_controller
            velocity_controllers

          vcs-repo-file-url: |
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/ros2_controllers.${{ env.ROS_DISTRO }}.repos?token=${{ secrets.GITHUB_TOKEN }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@v3.1.4
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v4.0.0
        with:
          name: colcon-logs-coverage-humble
          path: ros_ws/log
