name: Test ros2_controllers
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'
env:
  ROS_DISTRO: galactic

jobs:
  ros_industrial_ci:
    name: industrial ci
    runs-on: ubuntu-latest
    strategy:
     matrix:
      ROS_REPO: [main, testing]
    env:
     UPSTREAM_WORKSPACE: .github/workspace.repos
    steps:
     - uses: actions/checkout@v2
     - uses: ros-industrial/industrial_ci@master
       env:
        ROS_REPO: ${{ matrix.ROS_REPO }}

  ros-tooling-ci:
    name: ros-tooling ci
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{env.ROS_DISTRO}}
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{env.ROS_DISTRO}}
          # build all packages listed in the meta package
          package-name: |
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_trajectory_controller
            gripper_controllers
            position_controllers
            ros2_controllers_test_nodes
            velocity_controllers
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.github/workspace.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@v1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
