name: RHEL Humble Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 2 * * *'

jobs:
  humble_rhel_binary:
    name: Humble RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble
    container: ghcr.io/ros-controls/ros:humble-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2_controllers
      - name: Install dependencies
        run: |
          rosdep update
          rosdep install -iyr --from-path src/ros2_controllers || true
      - name: Build and test
        run: |
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source /opt/ros2_ws/install/setup.bash
          colcon build --packages-skip rqt_joint_trajectory_controller
          colcon test --packages-skip rqt_joint_trajectory_controller
          colcon test-result --verbose
