name: Debian Iron Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - iron
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/iron-debian-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_controllers.iron.repos'
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  iron_debian:
    name: Iron debian build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    with:
      ros_distro: iron
      upstream_workspace: ros2_controllers.iron.repos
      ref_for_scheduled_build: iron
      skip_packages: rqt_joint_trajectory_controller
