name: Jazzy - Debian Semi-Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/jazzy-debian-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_controllers.jazzy.repos'
      - '**.xml'
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  debian_semi_binary_build:
    name: Rolling debian build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    with:
      ros_distro: jazzy
      upstream_workspace: ros2_controllers.jazzy.repos
      ref_for_scheduled_build: jazzy
      skip_packages: rqt_joint_trajectory_controller
