name: Coverage Build - Kilted
on:
  workflow_dispatch:
  push:
    branches:
      - kilted
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '.github/workflows/kilted-coverage-build.yml'
      - '**.yaml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'codecov.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_controllers.kilted.repos'
  pull_request:
    branches:
      - kilted
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '.github/workflows/kilted-coverage-build.yml'
      - '**.yaml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'codecov.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_controllers.kilted.repos'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  coverage_kilted:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: kilted
