# Run linters automatically on pull requests.
name: Lint ros2_controllers
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, cppcheck, cpplint, flake8, pep257, uncrustify, xmllint]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.1
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: ${{ matrix.linter }}
        package-name:
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            joint_state_broadcaster
            joint_state_controller
            joint_trajectory_controller
            position_controllers
            ros2_controllers
            velocity_controllers
