name: Reusable industrial_ci Workflow with Cache
# Reusable action to simplify dealing with ROS/ROS2 industrial_ci builds with cache
# author: Denis Å togl <denis@stoglrobotics.de>

on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS2 distribution name'
        required: true
        type: string
      ref:
        description: 'Reference on which the repo should be checkout. Usually is this name of a branch or a tag.'
        required: true
        type: string
      ros2_repo_branch:
        description: 'Branch in the ros2/ros2 repozitory from which ".repos" should be used. Possible values: master (Rolling), humble, galactic, foxy.'
        default: 'master'
        required: false
        type: string

jobs:
  reusable_ros_tooling_source_build:
    name: ${{ inputs.ros_distro }} ubuntu-22.04
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ inputs.ros_distro }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ros-tooling/action-ros-ci@0.3.5
        with:
          target-ros2-distro: ${{ inputs.ros_distro }}
          # build all packages listed in the meta package
          package-name:
            ackermann_steering_controller
            admittance_controller
            bicycle_steering_controller
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            gripper_controllers
            imu_sensor_broadcaster
            joint_state_broadcaster
            joint_trajectory_controller
            position_controllers
            range_sensor_broadcaster
            ros2_controllers
            ros2_controllers_test_nodes
            rqt_joint_trajectory_controller
            steering_controllers_library
            tricycle_controller
            tricycle_steering_controller
            velocity_controllers

          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/${{ inputs.ros2_repo_branch }}/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/ros2_controllers.${{ inputs.ros_distro }}.repos?token=${{ secrets.GITHUB_TOKEN }}
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v3
        with:
          name: colcon-logs-ubuntu-22.04
          path: ros_ws/log
