name: Test ros2_controllers
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '17 8 * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@0.0.15
      - uses: ros-tooling/action-ros-ci@master
        with:
          package-name: joint_state_controller joint_trajectory_controller
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          vcs-repo-file-url: |
            "${{ github.workspace }}/travis/workspace.repos"
      - uses: actions/upload-artifact@master
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
